server:
  port: ${SERVER_PORT:${PORT:8080}}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: wiram-spring-backend
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: updatehe